CREATE TABLE "cards" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"rate" double precision DEFAULT 5 NOT NULL,
	"offer_short" text DEFAULT '' NOT NULL,
	"offer_short_sum" text DEFAULT '' NOT NULL,
	"grace_period" text DEFAULT '' NOT NULL,
	"service" text DEFAULT '' NOT NULL,
	"opening_card" text DEFAULT '' NOT NULL,
	"cashback" text DEFAULT '' NOT NULL,
	"release_date" text DEFAULT '' NOT NULL,
	"credits" text DEFAULT '' NOT NULL,
	"additionally" text DEFAULT '' NOT NULL,
	"registration" text DEFAULT '' NOT NULL,
	"term" text DEFAULT '' NOT NULL,
	"approval" text DEFAULT '' NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"advantage" text DEFAULT '' NOT NULL,
	"loan_sum" text DEFAULT '' NOT NULL,
	"age" text DEFAULT '' NOT NULL,
	"docs" text DEFAULT '' NOT NULL,
	"schedule" text DEFAULT '' NOT NULL,
	"license" text DEFAULT '' NOT NULL,
	"offer_detail" text DEFAULT '' NOT NULL,
	"image" text DEFAULT '' NOT NULL,
	"active" text DEFAULT '' NOT NULL,
	"site" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "loans" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text DEFAULT '' NOT NULL,
	"rate" double precision DEFAULT 5 NOT NULL,
	"offer_short" text DEFAULT '' NOT NULL,
	"offer_short_sum" text DEFAULT '' NOT NULL,
	"grace_period" text DEFAULT '' NOT NULL,
	"service" text DEFAULT '' NOT NULL,
	"opening_card" text DEFAULT '' NOT NULL,
	"cashback" text DEFAULT '' NOT NULL,
	"release_date" text DEFAULT '' NOT NULL,
	"credits" text DEFAULT '' NOT NULL,
	"additionally" text DEFAULT '' NOT NULL,
	"registration" text DEFAULT '' NOT NULL,
	"term" text DEFAULT '' NOT NULL,
	"approval" text DEFAULT '' NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"advantage" text DEFAULT '' NOT NULL,
	"loan_sum" text DEFAULT '' NOT NULL,
	"age" text DEFAULT '' NOT NULL,
	"docs" text DEFAULT '' NOT NULL,
	"schedule" text DEFAULT '' NOT NULL,
	"license" text DEFAULT '' NOT NULL,
	"offer_detail" text DEFAULT '' NOT NULL,
	"image" text DEFAULT '' NOT NULL,
	"active" text DEFAULT '' NOT NULL,
	"site" text DEFAULT '' NOT NULL
);
